### ISSUE TITLE
Terimakasih dataset nya

### ISSUE THREAD

**Issue by cahya-wirawan** [Wikidepia/SQuAD-id#1]
Saya sudah lama mau terjemahkan squad dataset ke indonesia, cuma belum kesampaian terus. Jadi senang sekali kalau sekarang sudah ada yg terjemahin :-) btw, bagaimana diterjemahin nya? apakah pakai google translator, opennmt, mariannmt, crowd sourcing atau diterjemahkan sama translator bayaran?

Btw, gimana kalau dataset nya di taro ke huggingface/datasets? kalau mau, nanti saya bisa buat kan. Atau mas mungkin mau buat sendiri?

**Comment by Wikidepia** [comment]
Terimakasih pak sudah melihat dataset ini.

Untuk nerjemahinnya cuma pakai google translate aja.
Untuk answer_start masih menggunakan fungsi find() dari Python karena memang sulit untuk mengalign jawaban & context. Jadi beberapa pertanyaan agak ngaco 😅. 

Silahkan pak kalau mau ditaruh ke huggingface/dataset.

**Comment by cahya-wirawan** [comment]
Tadinya mau coba Translate-Align-Retrieve https://github.com/ccasimiro88/TranslateAlignRetrieve yg dipakai untuk  spanish SQuad. Ini buat align jawabanya dng context, mungkin dengan cara spt itu, hasil dataset nya lebih bagus.

**Comment by cahya-wirawan** [comment]
Btw, mas namanya siapa? Akmal bukan?

**Comment by Wikidepia** [comment]
> Btw, mas namanya siapa? Akmal bukan?

Iya

**Comment by Wikidepia** [comment]
Closed. Silahkan reopen kalau dibutuhkan
